#!/bin/bash
# generated by gen_inputs_water.py; use run_water_chain.py to run it with timing
# the WSL2 host deadlocks under the default caching allocator; harmless elsewhere
set -euo pipefail
cd "$(dirname "$0")"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
(cd s1 && dp --pt train input.yaml)
(cd s2 && dp --pt train input.yaml --init-model ../s1/model.ckpt-18000.pt)
(cd s3 && dp --pt train input.yaml --init-model ../s2/model.ckpt-18000.pt)
(cd s4 && dp --pt train input.yaml --init-model ../s3/model.ckpt-18000.pt)
(cd s5 && dp --pt train input.yaml --init-model ../s4/model.ckpt-18000.pt)
(cd s6 && dp --pt train input.yaml --init-model ../s5/model.ckpt-18000.pt)
(cd s7 && dp --pt train input.yaml --init-model ../s6/model.ckpt-45000.pt)
