"""Generate an extension config from the campaign's 80k config.

Why: over the last 10k steps of the campaign the force error was flat
(window ratio 0.999) but the energy error was still falling (0.96 train / 0.905
val, averaged over 10 display rows so the 3-frame sampling noise cancels), and
the fall tracks the LR level. So the energy question needs more annealing time,
not a lower LR.

Two facts fix the protocol, both from the deepmd source:

  * `--restart` continues the GLOBAL step counter
    (`pt/train/training.py:452`, `start_step = train_infos["step"]`), and
  * `stop_steps` is built from the config's `numb_steps`, not from the steps
    remaining (`pt/train/training.py:281`).

The second one is the trap. Because the staircase is restretched over the new
total, a SHORTER extension reheats LESS, not more: to 120k the first new step
resumes at 1.07e-06, to 160k at 5.93e-06.

The schedule model (`value`, `final_lr`) is not guessed - it is checked against
the real `lr` column of the 80k run's `lcurve.out`, which it reproduces at every
one of the 80 logged steps to within the log's 3-significant-digit rounding
(max residual 2.7%). Two conventions that check pinned down, and that the
obvious reading gets wrong:

  * the level is `step // decay_steps` applied to the step ABOUT to be taken, so
    the lr printed at step s is the level of `(s-1)//ds`;
  * the run executes steps 1..N, so the highest level it ever applies is
    `N//ds - 1`, and the nominal `stop_lr` belongs to the level AFTER that. A run
    therefore never quite reaches its own floor: the 80k run's last lr was
    6.66e-08, not the 3.51e-08 floor. `final_lr` models that, and it is the
    reference the reheat is measured against.

Only two scalars change. seed, LR endpoints, decay_steps, loss prefs, data
systems, save_freq and disp_freq are copied verbatim, so the extension is a pure
step-budget change and any difference is attributable to the longer anneal.
`max_ckpt_keep` is raised so the new checkpoints do not evict the original
40k-80k ones (24.7 MB each).

Usage:
    python gen_extend_inputs.py --from 80000 --to 120000   # stage 1
    python gen_extend_inputs.py --from 120000 --to 160000  # stage 2
    python gen_extend_inputs.py --from 80000 --to 120000 --check
"""
import argparse
import math
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RUNS = os.path.join(HERE, "runs")
SRC = "input.yaml"

START_LR, STOP_LR, DECAY_STEPS = 0.001, 3.51e-8, 5000

NOTE = """# EXTENSION {frm} -> {to} - generated by gen_extend_inputs.py from input.yaml.
# Launch with:  ./run_extend.sh --from {frm} --to {to}
#   or:  dp --pt train {dst} --restart <abs>/model.ckpt-{frm}.pt
# --restart keeps the global step, so the {levels}-level staircase resumes at
# {resume:.3g} - {reheat:.0f}x the {prev_final:.3g} the {frmk}k run ended on - and
# anneals through {extra} more levels to {final:.3g}. (A run never quite reaches the
# nominal stop_lr {stop:.3g}: it applies levels 0..N/ds-1 only.) Everything else is
# byte-identical to input.yaml.
"""


def schedule(stop_steps, decay_steps=DECAY_STEPS, start_lr=START_LR, stop_lr=STOP_LR):
    """Mirror LearningRateExp.__init__: clamp decay_steps, then the ladder."""
    ds = decay_steps
    if ds >= stop_steps:
        ds = 100 if stop_steps // 10 > 100 else stop_steps // 100 + 1
    rate = math.exp(math.log(stop_lr / start_lr) / (stop_steps / ds))
    return ds, rate


def value(step, ds, rate, start_lr=START_LR, floor=STOP_LR):
    """LR applied to the step ABOUT to be taken, i.e. level step // ds."""
    return max(start_lr * rate ** (step // ds), floor)


def final_lr(n_steps, decay_steps=DECAY_STEPS, start_lr=START_LR, stop_lr=STOP_LR):
    """LR of the last level a run of n_steps actually applies (level N//ds - 1)."""
    ds, rate = schedule(n_steps, decay_steps, start_lr, stop_lr)
    return max(start_lr * rate ** (n_steps // ds - 1), stop_lr)


def build(src_text, frm, to, keep):
    out = src_text
    # a silent no-op here would launch an "extension" that trains nothing, so
    # both edits are asserted to land exactly once.
    for pat, rep in ((rf"^(\s*numb_steps:\s*)\d+\s*$", rf"\g<1>{to}"),
                     (rf"^(\s*max_ckpt_keep:\s*)\d+\s*$", rf"\g<1>{keep}")):
        out, k = re.subn(pat, rep, out, flags=re.M)
        assert k == 1, f"expected exactly one match for {pat!r}, got {k}"

    ds, rate = schedule(to)
    resume = value(frm, ds, rate)
    head = NOTE.format(frm=frm, to=to, frmk=frm // 1000, dst=f"input_{to // 1000}k.yaml",
                       levels=int(to / ds), extra=int(to / ds) - int(frm / ds),
                       resume=resume, reheat=resume / final_lr(frm), prev_final=final_lr(frm),
                       final=final_lr(to), stop=STOP_LR)
    return head + out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--from", dest="frm", type=int, default=80000)
    ap.add_argument("--to", dest="to", type=int, default=120000)
    ap.add_argument("--keep", type=int, default=0, help="max_ckpt_keep (0 = auto)")
    ap.add_argument("--check", action="store_true", help="print the schedule and exit")
    args = ap.parse_args()
    if args.to <= args.frm:
        raise SystemExit(f"--to ({args.to}) must exceed --from ({args.frm})")

    extra = max(1, (args.to - args.frm) // 10000)
    keep = args.keep or extra + 7
    dst = f"input_{args.to // 1000}k.yaml"

    ds, rate = schedule(args.to)
    resume = value(args.frm, ds, rate)
    prev_final = final_lr(args.frm)
    print(f"to {args.to}: decay_steps {ds}, decay_rate {rate:.6f}, {int(args.to / ds)} levels")
    print(f"  the {args.frm // 1000}k run ended on LR {prev_final:.4e} (level {int(args.frm / ds) - 1})")
    print(f"  resume at step {args.frm}: LR {resume:.4e}  ({resume / prev_final:.1f}x reheat)")
    print(f"  anneals through {int(args.to / ds) - int(args.frm / ds)} more levels to {final_lr(args.to):.4e}")
    print(f"  max_ckpt_keep {keep}  ->  {dst}")
    if args.check:
        return 0

    n = 0
    for name in sorted(os.listdir(RUNS)):
        rundir = os.path.join(RUNS, name)
        src = os.path.join(rundir, SRC)
        if not os.path.isfile(src):
            print(f"  skip {name}: no {SRC}")
            continue
        with open(src) as fh:
            text = fh.read()
        with open(os.path.join(rundir, dst), "w") as fh:
            fh.write(build(text, args.frm, args.to, keep))
        n += 1
        print(f"  wrote {name}/{dst}")
    print(f"\n{n} config(s) written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
